# Generated by Django 6.0.1 on 2026-01-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiggyDB',
            fields=[
                ('Mobile_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('Bill_no', models.IntegerField()),
                ('Items_no', models.IntegerField()),
            ],
        ),
    ]
